/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmartListRouteImport } from './routes/smart-list'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealsIdRouteImport } from './routes/deals.$id'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SmartListRoute = SmartListRouteImport.update({
  id: '/smart-list',
  path: '/smart-list',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIdRoute = DealsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DealsRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/coupons': typeof CouponsRoute
  '/deals': typeof DealsRouteWithChildren
  '/smart-list': typeof SmartListRoute
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/deals/$id': typeof DealsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/coupons': typeof CouponsRoute
  '/deals': typeof DealsRouteWithChildren
  '/smart-list': typeof SmartListRoute
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/deals/$id': typeof DealsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/coupons': typeof CouponsRoute
  '/deals': typeof DealsRouteWithChildren
  '/smart-list': typeof SmartListRoute
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/deals/$id': typeof DealsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/coupons'
    | '/deals'
    | '/smart-list'
    | '/api/chat'
    | '/api/stt'
    | '/api/tts'
    | '/deals/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/coupons'
    | '/deals'
    | '/smart-list'
    | '/api/chat'
    | '/api/stt'
    | '/api/tts'
    | '/deals/$id'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/coupons'
    | '/deals'
    | '/smart-list'
    | '/api/chat'
    | '/api/stt'
    | '/api/tts'
    | '/deals/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CouponsRoute: typeof CouponsRoute
  DealsRoute: typeof DealsRouteWithChildren
  SmartListRoute: typeof SmartListRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/smart-list': {
      id: '/smart-list'
      path: '/smart-list'
      fullPath: '/smart-list'
      preLoaderRoute: typeof SmartListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$id': {
      id: '/deals/$id'
      path: '/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof DealsIdRouteImport
      parentRoute: typeof DealsRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DealsRouteChildren {
  DealsIdRoute: typeof DealsIdRoute
}

const DealsRouteChildren: DealsRouteChildren = {
  DealsIdRoute: DealsIdRoute,
}

const DealsRouteWithChildren = DealsRoute._addFileChildren(DealsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CouponsRoute: CouponsRoute,
  DealsRoute: DealsRouteWithChildren,
  SmartListRoute: SmartListRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
