/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SyncPartnersRouteImport } from './routes/sync-partners'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SocialOffersRouteImport } from './routes/social-offers'
import { Route as SmartListRouteImport } from './routes/smart-list'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShowroomRouteImport } from './routes/showroom'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as ProRouteImport } from './routes/pro'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AffiliateSetupRouteImport } from './routes/affiliate-setup'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HkeeemIndexRouteImport } from './routes/hkeeem.index'
import { Route as RewardsIdRouteImport } from './routes/rewards.$id'
import { Route as HkeeemProductRouteImport } from './routes/hkeeem.product'
import { Route as HkeeemNearbyRouteImport } from './routes/hkeeem.nearby'
import { Route as HkeeemChatRouteImport } from './routes/hkeeem.chat'
import { Route as DealsPandaVsOthaimComparisonRouteImport } from './routes/deals.panda-vs-othaim-comparison'
import { Route as DealsIdRouteImport } from './routes/deals.$id'
import { Route as CouponsIdRouteImport } from './routes/coupons.$id'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVisitorsRouteImport } from './routes/_authenticated/visitors'
import { Route as AuthenticatedSyncLogRouteImport } from './routes/_authenticated/sync-log'
import { Route as AuthenticatedSearchConsoleRouteImport } from './routes/_authenticated/search-console'
import { Route as AuthenticatedNoonSettingsRouteImport } from './routes/_authenticated/noon-settings'
import { Route as AuthenticatedMerchantReviewRouteImport } from './routes/_authenticated/merchant-review'
import { Route as AuthenticatedMerchantRouteImport } from './routes/_authenticated/merchant'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedDealsAdminRouteImport } from './routes/_authenticated/deals-admin'
import { Route as AuthenticatedDealReportsRouteImport } from './routes/_authenticated/deal-reports'
import { Route as AuthenticatedBuildErrorsRouteImport } from './routes/_authenticated/build-errors'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicPostbackNetworkRouteImport } from './routes/api/public/postback.$network'
import { Route as ApiPublicHooksWeeklyReportRouteImport } from './routes/api/public/hooks/weekly-report'
import { Route as ApiPublicHooksSyncExternalDealsRouteImport } from './routes/api/public/hooks/sync-external-deals'
import { Route as ApiPublicHooksStoreBotRouteImport } from './routes/api/public/hooks/store-bot'
import { Route as ApiPublicHooksSocialSyncRouteImport } from './routes/api/public/hooks/social-sync'
import { Route as ApiPublicHooksShowroomSyncRouteImport } from './routes/api/public/hooks/showroom-sync'
import { Route as ApiPublicHooksSearchConsoleSnapshotRouteImport } from './routes/api/public/hooks/search-console-snapshot'
import { Route as ApiPublicHooksOfficePicksRouteImport } from './routes/api/public/hooks/office-picks'
import { Route as ApiPublicHooksHarajSyncRouteImport } from './routes/api/public/hooks/haraj-sync'
import { Route as ApiPublicHooksDealPushRouteImport } from './routes/api/public/hooks/deal-push'
import { Route as ApiPublicGoDealIdRouteImport } from './routes/api/public/go.$dealId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncPartnersRoute = SyncPartnersRouteImport.update({
  id: '/sync-partners',
  path: '/sync-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialOffersRoute = SocialOffersRouteImport.update({
  id: '/social-offers',
  path: '/social-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartListRoute = SmartListRouteImport.update({
  id: '/smart-list',
  path: '/smart-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowroomRoute = ShowroomRouteImport.update({
  id: '/showroom',
  path: '/showroom',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateSetupRoute = AffiliateSetupRouteImport.update({
  id: '/affiliate-setup',
  path: '/affiliate-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HkeeemIndexRoute = HkeeemIndexRouteImport.update({
  id: '/hkeeem/',
  path: '/hkeeem/',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsIdRoute = RewardsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RewardsRoute,
} as any)
const HkeeemProductRoute = HkeeemProductRouteImport.update({
  id: '/hkeeem/product',
  path: '/hkeeem/product',
  getParentRoute: () => rootRouteImport,
} as any)
const HkeeemNearbyRoute = HkeeemNearbyRouteImport.update({
  id: '/hkeeem/nearby',
  path: '/hkeeem/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const HkeeemChatRoute = HkeeemChatRouteImport.update({
  id: '/hkeeem/chat',
  path: '/hkeeem/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsPandaVsOthaimComparisonRoute =
  DealsPandaVsOthaimComparisonRouteImport.update({
    id: '/panda-vs-othaim-comparison',
    path: '/panda-vs-othaim-comparison',
    getParentRoute: () => DealsRoute,
  } as any)
const DealsIdRoute = DealsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DealsRoute,
} as any)
const CouponsIdRoute = CouponsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CouponsRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyContentSyncRoute =
  ApiPublicHooksDailyContentSyncRouteImport.update({
    id: '/api/public/hooks/daily-content-sync',
    path: '/api/public/hooks/daily-content-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDealPushRoute = ApiPublicHooksDealPushRouteImport.update({
  id: '/api/public/hooks/deal-push',
  path: '/api/public/hooks/deal-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisitorsRoute = AuthenticatedVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSyncLogRoute = AuthenticatedSyncLogRouteImport.update({
  id: '/sync-log',
  path: '/sync-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchConsoleRoute =
  AuthenticatedSearchConsoleRouteImport.update({
    id: '/search-console',
    path: '/search-console',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNoonSettingsRoute =
  AuthenticatedNoonSettingsRouteImport.update({
    id: '/noon-settings',
    path: '/noon-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMerchantReviewRoute =
  AuthenticatedMerchantReviewRouteImport.update({
    id: '/merchant-review',
    path: '/merchant-review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMerchantRoute = AuthenticatedMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsAdminRoute = AuthenticatedDealsAdminRouteImport.update({
  id: '/deals-admin',
  path: '/deals-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealReportsRoute =
  AuthenticatedDealReportsRouteImport.update({
    id: '/deal-reports',
    path: '/deal-reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuildErrorsRoute =
  AuthenticatedBuildErrorsRouteImport.update({
    id: '/build-errors',
    path: '/build-errors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPostbackNetworkRoute =
  ApiPublicPostbackNetworkRouteImport.update({
    id: '/api/public/postback/$network',
    path: '/api/public/postback/$network',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklyReportRoute =
  ApiPublicHooksWeeklyReportRouteImport.update({
    id: '/api/public/hooks/weekly-report',
    path: '/api/public/hooks/weekly-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncExternalDealsRoute =
  ApiPublicHooksSyncExternalDealsRouteImport.update({
    id: '/api/public/hooks/sync-external-deals',
    path: '/api/public/hooks/sync-external-deals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStoreBotRoute = ApiPublicHooksStoreBotRouteImport.update({
  id: '/api/public/hooks/store-bot',
  path: '/api/public/hooks/store-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSocialSyncRoute =
  ApiPublicHooksSocialSyncRouteImport.update({
    id: '/api/public/hooks/social-sync',
    path: '/api/public/hooks/social-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksShowroomSyncRoute =
  ApiPublicHooksShowroomSyncRouteImport.update({
    id: '/api/public/hooks/showroom-sync',
    path: '/api/public/hooks/showroom-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSearchConsoleSnapshotRoute =
  ApiPublicHooksSearchConsoleSnapshotRouteImport.update({
    id: '/api/public/hooks/search-console-snapshot',
    path: '/api/public/hooks/search-console-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOfficePicksRoute =
  ApiPublicHooksOfficePicksRouteImport.update({
    id: '/api/public/hooks/office-picks',
    path: '/api/public/hooks/office-picks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksHarajSyncRoute = ApiPublicHooksHarajSyncRouteImport.update({
  id: '/api/public/hooks/haraj-sync',
  path: '/api/public/hooks/haraj-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDealPushRoute = ApiPublicHooksDealPushRouteImport.update({
  id: '/api/public/hooks/deal-push',
  path: '/api/public/hooks/deal-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoDealIdRoute = ApiPublicGoDealIdRouteImport.update({
  id: '/api/public/go/$dealId',
  path: '/api/public/go/$dealId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/affiliate-setup': typeof AffiliateSetupRoute
  '/agents': typeof AgentsRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/cars': typeof CarsRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/coupons': typeof CouponsRouteWithChildren
  '/deals': typeof DealsRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/hkeeem-shopping': typeof HkeeemShoppingRoute
  '/hkeeem-showroom': typeof HkeeemShowroomRoute
  '/maps': typeof MapsRoute
  '/market': typeof MarketRoute
  '/notifications': typeof NotificationsRoute
  '/office': typeof OfficeRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/real-estate': typeof RealEstateRoute
  '/rewards': typeof RewardsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/showroom': typeof ShowroomRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smart-list': typeof SmartListRoute
  '/social-offers': typeof SocialOffersRoute
  '/stores': typeof StoresRoute
  '/sync-partners': typeof SyncPartnersRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/build-errors': typeof AuthenticatedBuildErrorsRoute
  '/deal-reports': typeof AuthenticatedDealReportsRoute
  '/deals-admin': typeof AuthenticatedDealsAdminRoute
  '/me': typeof AuthenticatedMeRoute
  '/merchant': typeof AuthenticatedMerchantRoute
  '/merchant-review': typeof AuthenticatedMerchantReviewRoute
  '/noon-settings': typeof AuthenticatedNoonSettingsRoute
  '/search-console': typeof AuthenticatedSearchConsoleRoute
  '/sync-log': typeof AuthenticatedSyncLogRoute
  '/visitors': typeof AuthenticatedVisitorsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/coupons/$id': typeof CouponsIdRoute
  '/deals/$id': typeof DealsIdRoute
  '/deals/panda-vs-othaim-comparison': typeof DealsPandaVsOthaimComparisonRoute
  '/hkeeem/chat': typeof HkeeemChatRoute
  '/hkeeem/nearby': typeof HkeeemNearbyRoute
  '/hkeeem/product': typeof HkeeemProductRoute
  '/rewards/$id': typeof RewardsIdRoute
  '/hkeeem/': typeof HkeeemIndexRoute
  '/api/public/go/$dealId': typeof ApiPublicGoDealIdRoute
  '/api/public/hooks/daily-content-sync': typeof ApiPublicHooksDailyContentSyncRoute
  '/api/public/hooks/deal-push': typeof ApiPublicHooksDealPushRoute
  '/api/public/hooks/haraj-sync': typeof ApiPublicHooksHarajSyncRoute
  '/api/public/hooks/office-picks': typeof ApiPublicHooksOfficePicksRoute
  '/api/public/hooks/search-console-snapshot': typeof ApiPublicHooksSearchConsoleSnapshotRoute
  '/api/public/hooks/showroom-sync': typeof ApiPublicHooksShowroomSyncRoute
  '/api/public/hooks/social-sync': typeof ApiPublicHooksSocialSyncRoute
  '/api/public/hooks/store-bot': typeof ApiPublicHooksStoreBotRoute
  '/api/public/hooks/sync-external-deals': typeof ApiPublicHooksSyncExternalDealsRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
  '/api/public/postback/$network': typeof ApiPublicPostbackNetworkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/affiliate-setup': typeof AffiliateSetupRoute
  '/agents': typeof AgentsRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/cars': typeof CarsRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/coupons': typeof CouponsRouteWithChildren
  '/deals': typeof DealsRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/hkeeem-shopping': typeof HkeeemShoppingRoute
  '/hkeeem-showroom': typeof HkeeemShowroomRoute
  '/maps': typeof MapsRoute
  '/market': typeof MarketRoute
  '/notifications': typeof NotificationsRoute
  '/office': typeof OfficeRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/real-estate': typeof RealEstateRoute
  '/rewards': typeof RewardsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/showroom': typeof ShowroomRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smart-list': typeof SmartListRoute
  '/social-offers': typeof SocialOffersRoute
  '/stores': typeof StoresRoute
  '/sync-partners': typeof SyncPartnersRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/build-errors': typeof AuthenticatedBuildErrorsRoute
  '/deal-reports': typeof AuthenticatedDealReportsRoute
  '/deals-admin': typeof AuthenticatedDealsAdminRoute
  '/me': typeof AuthenticatedMeRoute
  '/merchant': typeof AuthenticatedMerchantRoute
  '/merchant-review': typeof AuthenticatedMerchantReviewRoute
  '/noon-settings': typeof AuthenticatedNoonSettingsRoute
  '/search-console': typeof AuthenticatedSearchConsoleRoute
  '/sync-log': typeof AuthenticatedSyncLogRoute
  '/visitors': typeof AuthenticatedVisitorsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/coupons/$id': typeof CouponsIdRoute
  '/deals/$id': typeof DealsIdRoute
  '/deals/panda-vs-othaim-comparison': typeof DealsPandaVsOthaimComparisonRoute
  '/hkeeem/chat': typeof HkeeemChatRoute
  '/hkeeem/nearby': typeof HkeeemNearbyRoute
  '/hkeeem/product': typeof HkeeemProductRoute
  '/rewards/$id': typeof RewardsIdRoute
  '/hkeeem': typeof HkeeemIndexRoute
  '/api/public/go/$dealId': typeof ApiPublicGoDealIdRoute
  '/api/public/hooks/daily-content-sync': typeof ApiPublicHooksDailyContentSyncRoute
  '/api/public/hooks/deal-push': typeof ApiPublicHooksDealPushRoute
  '/api/public/hooks/haraj-sync': typeof ApiPublicHooksHarajSyncRoute
  '/api/public/hooks/office-picks': typeof ApiPublicHooksOfficePicksRoute
  '/api/public/hooks/search-console-snapshot': typeof ApiPublicHooksSearchConsoleSnapshotRoute
  '/api/public/hooks/showroom-sync': typeof ApiPublicHooksShowroomSyncRoute
  '/api/public/hooks/social-sync': typeof ApiPublicHooksSocialSyncRoute
  '/api/public/hooks/store-bot': typeof ApiPublicHooksStoreBotRoute
  '/api/public/hooks/sync-external-deals': typeof ApiPublicHooksSyncExternalDealsRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
  '/api/public/postback/$network': typeof ApiPublicPostbackNetworkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ads': typeof AdsRoute
  '/affiliate-setup': typeof AffiliateSetupRoute
  '/agents': typeof AgentsRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/cars': typeof CarsRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/coupons': typeof CouponsRouteWithChildren
  '/deals': typeof DealsRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/hkeeem-shopping': typeof HkeeemShoppingRoute
  '/hkeeem-showroom': typeof HkeeemShowroomRoute
  '/maps': typeof MapsRoute
  '/market': typeof MarketRoute
  '/notifications': typeof NotificationsRoute
  '/office': typeof OfficeRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/real-estate': typeof RealEstateRoute
  '/rewards': typeof RewardsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/showroom': typeof ShowroomRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smart-list': typeof SmartListRoute
  '/social-offers': typeof SocialOffersRoute
  '/stores': typeof StoresRoute
  '/sync-partners': typeof SyncPartnersRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/build-errors': typeof AuthenticatedBuildErrorsRoute
  '/_authenticated/deal-reports': typeof AuthenticatedDealReportsRoute
  '/_authenticated/deals-admin': typeof AuthenticatedDealsAdminRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/merchant': typeof AuthenticatedMerchantRoute
  '/_authenticated/merchant-review': typeof AuthenticatedMerchantReviewRoute
  '/_authenticated/noon-settings': typeof AuthenticatedNoonSettingsRoute
  '/_authenticated/search-console': typeof AuthenticatedSearchConsoleRoute
  '/_authenticated/sync-log': typeof AuthenticatedSyncLogRoute
  '/_authenticated/visitors': typeof AuthenticatedVisitorsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/coupons/$id': typeof CouponsIdRoute
  '/deals/$id': typeof DealsIdRoute
  '/deals/panda-vs-othaim-comparison': typeof DealsPandaVsOthaimComparisonRoute
  '/hkeeem/chat': typeof HkeeemChatRoute
  '/hkeeem/nearby': typeof HkeeemNearbyRoute
  '/hkeeem/product': typeof HkeeemProductRoute
  '/rewards/$id': typeof RewardsIdRoute
  '/hkeeem/': typeof HkeeemIndexRoute
  '/api/public/go/$dealId': typeof ApiPublicGoDealIdRoute
  '/api/public/hooks/daily-content-sync': typeof ApiPublicHooksDailyContentSyncRoute
  '/api/public/hooks/deal-push': typeof ApiPublicHooksDealPushRoute
  '/api/public/hooks/haraj-sync': typeof ApiPublicHooksHarajSyncRoute
  '/api/public/hooks/office-picks': typeof ApiPublicHooksOfficePicksRoute
  '/api/public/hooks/search-console-snapshot': typeof ApiPublicHooksSearchConsoleSnapshotRoute
  '/api/public/hooks/showroom-sync': typeof ApiPublicHooksShowroomSyncRoute
  '/api/public/hooks/social-sync': typeof ApiPublicHooksSocialSyncRoute
  '/api/public/hooks/store-bot': typeof ApiPublicHooksStoreBotRoute
  '/api/public/hooks/sync-external-deals': typeof ApiPublicHooksSyncExternalDealsRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
  '/api/public/postback/$network': typeof ApiPublicPostbackNetworkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/affiliate-setup'
    | '/agents'
    | '/analysis'
    | '/auth'
    | '/cars'
    | '/chat'
    | '/compare'
    | '/coupons'
    | '/deals'
    | '/delete-account'
    | '/hkeeem-shopping'
    | '/hkeeem-showroom'
    | '/maps'
    | '/market'
    | '/notifications'
    | '/office'
    | '/privacy'
    | '/pro'
    | '/real-estate'
    | '/rewards'
    | '/settings'
    | '/shop'
    | '/showroom'
    | '/sitemap.xml'
    | '/smart-list'
    | '/social-offers'
    | '/stores'
    | '/sync-partners'
    | '/terms'
    | '/admin'
    | '/build-errors'
    | '/deal-reports'
    | '/deals-admin'
    | '/me'
    | '/merchant'
    | '/merchant-review'
    | '/noon-settings'
    | '/search-console'
    | '/sync-log'
    | '/visitors'
    | '/api/chat'
    | '/api/stt'
    | '/api/tts'
    | '/coupons/$id'
    | '/deals/$id'
    | '/deals/panda-vs-othaim-comparison'
    | '/hkeeem/chat'
    | '/hkeeem/nearby'
    | '/hkeeem/product'
    | '/rewards/$id'
    | '/hkeeem/'
    | '/api/public/go/$dealId'
    | '/api/public/hooks/daily-content-sync'
    | '/api/public/hooks/deal-push'
    | '/api/public/hooks/haraj-sync'
    | '/api/public/hooks/office-picks'
    | '/api/public/hooks/search-console-snapshot'
    | '/api/public/hooks/showroom-sync'
    | '/api/public/hooks/social-sync'
    | '/api/public/hooks/store-bot'
    | '/api/public/hooks/sync-external-deals'
    | '/api/public/hooks/weekly-report'
    | '/api/public/postback/$network'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/affiliate-setup'
    | '/agents'
    | '/analysis'
    | '/auth'
    | '/cars'
    | '/chat'
    | '/compare'
    | '/coupons'
    | '/deals'
    | '/delete-account'
    | '/hkeeem-shopping'
    | '/hkeeem-showroom'
    | '/maps'
    | '/market'
    | '/notifications'
    | '/office'
    | '/privacy'
    | '/pro'
    | '/real-estate'
    | '/rewards'
    | '/settings'
    | '/shop'
    | '/showroom'
    | '/sitemap.xml'
    | '/smart-list'
    | '/social-offers'
    | '/stores'
    | '/sync-partners'
    | '/terms'
    | '/admin'
    | '/build-errors'
    | '/deal-reports'
    | '/deals-admin'
    | '/me'
    | '/merchant'
    | '/merchant-review'
    | '/noon-settings'
    | '/search-console'
    | '/sync-log'
    | '/visitors'
    | '/api/chat'
    | '/api/stt'
    | '/api/tts'
    | '/coupons/$id'
    | '/deals/$id'
    | '/deals/panda-vs-othaim-comparison'
    | '/hkeeem/chat'
    | '/hkeeem/nearby'
    | '/hkeeem/product'
    | '/rewards/$id'
    | '/hkeeem'
    | '/api/public/go/$dealId'
    | '/api/public/hooks/daily-content-sync'
    | '/api/public/hooks/deal-push'
    | '/api/public/hooks/haraj-sync'
    | '/api/public/hooks/office-picks'
    | '/api/public/hooks/search-console-snapshot'
    | '/api/public/hooks/showroom-sync'
    | '/api/public/hooks/social-sync'
    | '/api/public/hooks/store-bot'
    | '/api/public/hooks/sync-external-deals'
    | '/api/public/hooks/weekly-report'
    | '/api/public/postback/$network'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ads'
    | '/affiliate-setup'
    | '/agents'
    | '/analysis'
    | '/auth'
    | '/cars'
    | '/chat'
    | '/compare'
    | '/coupons'
    | '/deals'
    | '/delete-account'
    | '/hkeeem-shopping'
    | '/hkeeem-showroom'
    | '/maps'
    | '/market'
    | '/notifications'
    | '/office'
    | '/privacy'
    | '/pro'
    | '/real-estate'
    | '/rewards'
    | '/settings'
    | '/shop'
    | '/showroom'
    | '/sitemap.xml'
    | '/smart-list'
    | '/social-offers'
    | '/stores'
    | '/sync-partners'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/build-errors'
    | '/_authenticated/deal-reports'
    | '/_authenticated/deals-admin'
    | '/_authenticated/me'
    | '/_authenticated/merchant'
    | '/_authenticated/merchant-review'
    | '/_authenticated/noon-settings'
    | '/_authenticated/search-console'
    | '/_authenticated/sync-log'
    | '/_authenticated/visitors'
    | '/api/chat'
    | '/api/stt'
    | '/api/tts'
    | '/coupons/$id'
    | '/deals/$id'
    | '/deals/panda-vs-othaim-comparison'
    | '/hkeeem/chat'
    | '/hkeeem/nearby'
    | '/hkeeem/product'
    | '/rewards/$id'
    | '/hkeeem/'
    | '/api/public/go/$dealId'
    | '/api/public/hooks/daily-content-sync'
    | '/api/public/hooks/deal-push'
    | '/api/public/hooks/haraj-sync'
    | '/api/public/hooks/office-picks'
    | '/api/public/hooks/search-console-snapshot'
    | '/api/public/hooks/showroom-sync'
    | '/api/public/hooks/social-sync'
    | '/api/public/hooks/store-bot'
    | '/api/public/hooks/sync-external-deals'
    | '/api/public/hooks/weekly-report'
    | '/api/public/postback/$network'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdsRoute: typeof AdsRoute
  AffiliateSetupRoute: typeof AffiliateSetupRoute
  AgentsRoute: typeof AgentsRoute
  AnalysisRoute: typeof AnalysisRoute
  AuthRoute: typeof AuthRoute
  CarsRoute: typeof CarsRoute
  ChatRoute: typeof ChatRoute
  CompareRoute: typeof CompareRoute
  CouponsRoute: typeof CouponsRouteWithChildren
  DealsRoute: typeof DealsRouteWithChildren
  DeleteAccountRoute: typeof DeleteAccountRoute
  HkeeemShoppingRoute: typeof HkeeemShoppingRoute
  HkeeemShowroomRoute: typeof HkeeemShowroomRoute
  MapsRoute: typeof MapsRoute
  MarketRoute: typeof MarketRoute
  NotificationsRoute: typeof NotificationsRoute
  OfficeRoute: typeof OfficeRoute
  PrivacyRoute: typeof PrivacyRoute
  ProRoute: typeof ProRoute
  RealEstateRoute: typeof RealEstateRoute
  RewardsRoute: typeof RewardsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  ShowroomRoute: typeof ShowroomRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SmartListRoute: typeof SmartListRoute
  SocialOffersRoute: typeof SocialOffersRoute
  StoresRoute: typeof StoresRoute
  SyncPartnersRoute: typeof SyncPartnersRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  HkeeemChatRoute: typeof HkeeemChatRoute
  HkeeemNearbyRoute: typeof HkeeemNearbyRoute
  HkeeemProductRoute: typeof HkeeemProductRoute
  HkeeemIndexRoute: typeof HkeeemIndexRoute
  ApiPublicGoDealIdRoute: typeof ApiPublicGoDealIdRoute
  ApiPublicHooksDailyContentSyncRoute: typeof ApiPublicHooksDailyContentSyncRoute
  ApiPublicHooksDealPushRoute: typeof ApiPublicHooksDealPushRoute
  ApiPublicHooksHarajSyncRoute: typeof ApiPublicHooksHarajSyncRoute
  ApiPublicHooksOfficePicksRoute: typeof ApiPublicHooksOfficePicksRoute
  ApiPublicHooksSearchConsoleSnapshotRoute: typeof ApiPublicHooksSearchConsoleSnapshotRoute
  ApiPublicHooksShowroomSyncRoute: typeof ApiPublicHooksShowroomSyncRoute
  ApiPublicHooksSocialSyncRoute: typeof ApiPublicHooksSocialSyncRoute
  ApiPublicHooksStoreBotRoute: typeof ApiPublicHooksStoreBotRoute
  ApiPublicHooksSyncExternalDealsRoute: typeof ApiPublicHooksSyncExternalDealsRoute
  ApiPublicHooksWeeklyReportRoute: typeof ApiPublicHooksWeeklyReportRoute
  ApiPublicPostbackNetworkRoute: typeof ApiPublicPostbackNetworkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync-partners': {
      id: '/sync-partners'
      path: '/sync-partners'
      fullPath: '/sync-partners'
      preLoaderRoute: typeof SyncPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-offers': {
      id: '/social-offers'
      path: '/social-offers'
      fullPath: '/social-offers'
      preLoaderRoute: typeof SocialOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-list': {
      id: '/smart-list'
      path: '/smart-list'
      fullPath: '/smart-list'
      preLoaderRoute: typeof SmartListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showroom': {
      id: '/showroom'
      path: '/showroom'
      fullPath: '/showroom'
      preLoaderRoute: typeof ShowroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-setup': {
      id: '/affiliate-setup'
      path: '/affiliate-setup'
      fullPath: '/affiliate-setup'
      preLoaderRoute: typeof AffiliateSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hkeeem/': {
      id: '/hkeeem/'
      path: '/hkeeem'
      fullPath: '/hkeeem/'
      preLoaderRoute: typeof HkeeemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards/$id': {
      id: '/rewards/$id'
      path: '/$id'
      fullPath: '/rewards/$id'
      preLoaderRoute: typeof RewardsIdRouteImport
      parentRoute: typeof RewardsRoute
    }
    '/hkeeem/product': {
      id: '/hkeeem/product'
      path: '/hkeeem/product'
      fullPath: '/hkeeem/product'
      preLoaderRoute: typeof HkeeemProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hkeeem/nearby': {
      id: '/hkeeem/nearby'
      path: '/hkeeem/nearby'
      fullPath: '/hkeeem/nearby'
      preLoaderRoute: typeof HkeeemNearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hkeeem/chat': {
      id: '/hkeeem/chat'
      path: '/hkeeem/chat'
      fullPath: '/hkeeem/chat'
      preLoaderRoute: typeof HkeeemChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/panda-vs-othaim-comparison': {
      id: '/deals/panda-vs-othaim-comparison'
      path: '/panda-vs-othaim-comparison'
      fullPath: '/deals/panda-vs-othaim-comparison'
      preLoaderRoute: typeof DealsPandaVsOthaimComparisonRouteImport
      parentRoute: typeof DealsRoute
    }
    '/deals/$id': {
      id: '/deals/$id'
      path: '/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof DealsIdRouteImport
      parentRoute: typeof DealsRoute
    }
    '/coupons/$id': {
      id: '/coupons/$id'
      path: '/$id'
      fullPath: '/coupons/$id'
      preLoaderRoute: typeof CouponsIdRouteImport
      parentRoute: typeof CouponsRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visitors': {
      id: '/_authenticated/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof AuthenticatedVisitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sync-log': {
      id: '/_authenticated/sync-log'
      path: '/sync-log'
      fullPath: '/sync-log'
      preLoaderRoute: typeof AuthenticatedSyncLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search-console': {
      id: '/_authenticated/search-console'
      path: '/search-console'
      fullPath: '/search-console'
      preLoaderRoute: typeof AuthenticatedSearchConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/noon-settings': {
      id: '/_authenticated/noon-settings'
      path: '/noon-settings'
      fullPath: '/noon-settings'
      preLoaderRoute: typeof AuthenticatedNoonSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merchant-review': {
      id: '/_authenticated/merchant-review'
      path: '/merchant-review'
      fullPath: '/merchant-review'
      preLoaderRoute: typeof AuthenticatedMerchantReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merchant': {
      id: '/_authenticated/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof AuthenticatedMerchantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals-admin': {
      id: '/_authenticated/deals-admin'
      path: '/deals-admin'
      fullPath: '/deals-admin'
      preLoaderRoute: typeof AuthenticatedDealsAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deal-reports': {
      id: '/_authenticated/deal-reports'
      path: '/deal-reports'
      fullPath: '/deal-reports'
      preLoaderRoute: typeof AuthenticatedDealReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/build-errors': {
      id: '/_authenticated/build-errors'
      path: '/build-errors'
      fullPath: '/build-errors'
      preLoaderRoute: typeof AuthenticatedBuildErrorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/postback/$network': {
      id: '/api/public/postback/$network'
      path: '/api/public/postback/$network'
      fullPath: '/api/public/postback/$network'
      preLoaderRoute: typeof ApiPublicPostbackNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-report': {
      id: '/api/public/hooks/weekly-report'
      path: '/api/public/hooks/weekly-report'
      fullPath: '/api/public/hooks/weekly-report'
      preLoaderRoute: typeof ApiPublicHooksWeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-external-deals': {
      id: '/api/public/hooks/sync-external-deals'
      path: '/api/public/hooks/sync-external-deals'
      fullPath: '/api/public/hooks/sync-external-deals'
      preLoaderRoute: typeof ApiPublicHooksSyncExternalDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/store-bot': {
      id: '/api/public/hooks/store-bot'
      path: '/api/public/hooks/store-bot'
      fullPath: '/api/public/hooks/store-bot'
      preLoaderRoute: typeof ApiPublicHooksStoreBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/social-sync': {
      id: '/api/public/hooks/social-sync'
      path: '/api/public/hooks/social-sync'
      fullPath: '/api/public/hooks/social-sync'
      preLoaderRoute: typeof ApiPublicHooksSocialSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/showroom-sync': {
      id: '/api/public/hooks/showroom-sync'
      path: '/api/public/hooks/showroom-sync'
      fullPath: '/api/public/hooks/showroom-sync'
      preLoaderRoute: typeof ApiPublicHooksShowroomSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/search-console-snapshot': {
      id: '/api/public/hooks/search-console-snapshot'
      path: '/api/public/hooks/search-console-snapshot'
      fullPath: '/api/public/hooks/search-console-snapshot'
      preLoaderRoute: typeof ApiPublicHooksSearchConsoleSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/office-picks': {
      id: '/api/public/hooks/office-picks'
      path: '/api/public/hooks/office-picks'
      fullPath: '/api/public/hooks/office-picks'
      preLoaderRoute: typeof ApiPublicHooksOfficePicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/haraj-sync': {
      id: '/api/public/hooks/haraj-sync'
      path: '/api/public/hooks/haraj-sync'
      fullPath: '/api/public/hooks/haraj-sync'
      preLoaderRoute: typeof ApiPublicHooksHarajSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/deal-push': {
      id: '/api/public/hooks/deal-push'
      path: '/api/public/hooks/deal-push'
      fullPath: '/api/public/hooks/deal-push'
      preLoaderRoute: typeof ApiPublicHooksDealPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/go/$dealId': {
      id: '/api/public/go/$dealId'
      path: '/api/public/go/$dealId'
      fullPath: '/api/public/go/$dealId'
      preLoaderRoute: typeof ApiPublicGoDealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBuildErrorsRoute: typeof AuthenticatedBuildErrorsRoute
  AuthenticatedDealReportsRoute: typeof AuthenticatedDealReportsRoute
  AuthenticatedDealsAdminRoute: typeof AuthenticatedDealsAdminRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedMerchantRoute: typeof AuthenticatedMerchantRoute
  AuthenticatedMerchantReviewRoute: typeof AuthenticatedMerchantReviewRoute
  AuthenticatedNoonSettingsRoute: typeof AuthenticatedNoonSettingsRoute
  AuthenticatedSearchConsoleRoute: typeof AuthenticatedSearchConsoleRoute
  AuthenticatedSyncLogRoute: typeof AuthenticatedSyncLogRoute
  AuthenticatedVisitorsRoute: typeof AuthenticatedVisitorsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBuildErrorsRoute: AuthenticatedBuildErrorsRoute,
  AuthenticatedDealReportsRoute: AuthenticatedDealReportsRoute,
  AuthenticatedDealsAdminRoute: AuthenticatedDealsAdminRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedMerchantRoute: AuthenticatedMerchantRoute,
  AuthenticatedMerchantReviewRoute: AuthenticatedMerchantReviewRoute,
  AuthenticatedNoonSettingsRoute: AuthenticatedNoonSettingsRoute,
  AuthenticatedSearchConsoleRoute: AuthenticatedSearchConsoleRoute,
  AuthenticatedSyncLogRoute: AuthenticatedSyncLogRoute,
  AuthenticatedVisitorsRoute: AuthenticatedVisitorsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CouponsRouteChildren {
  CouponsIdRoute: typeof CouponsIdRoute
}

const CouponsRouteChildren: CouponsRouteChildren = {
  CouponsIdRoute: CouponsIdRoute,
}

const CouponsRouteWithChildren =
  CouponsRoute._addFileChildren(CouponsRouteChildren)

interface DealsRouteChildren {
  DealsIdRoute: typeof DealsIdRoute
  DealsPandaVsOthaimComparisonRoute: typeof DealsPandaVsOthaimComparisonRoute
}

const DealsRouteChildren: DealsRouteChildren = {
  DealsIdRoute: DealsIdRoute,
  DealsPandaVsOthaimComparisonRoute: DealsPandaVsOthaimComparisonRoute,
}

const DealsRouteWithChildren = DealsRoute._addFileChildren(DealsRouteChildren)

interface RewardsRouteChildren {
  RewardsIdRoute: typeof RewardsIdRoute
}

const RewardsRouteChildren: RewardsRouteChildren = {
  RewardsIdRoute: RewardsIdRoute,
}

const RewardsRouteWithChildren =
  RewardsRoute._addFileChildren(RewardsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdsRoute: AdsRoute,
  AffiliateSetupRoute: AffiliateSetupRoute,
  AgentsRoute: AgentsRoute,
  AnalysisRoute: AnalysisRoute,
  AuthRoute: AuthRoute,
  CarsRoute: CarsRoute,
  ChatRoute: ChatRoute,
  CompareRoute: CompareRoute,
  CouponsRoute: CouponsRouteWithChildren,
  DealsRoute: DealsRouteWithChildren,
  DeleteAccountRoute: DeleteAccountRoute,
  HkeeemShoppingRoute: HkeeemShoppingRoute,
  HkeeemShowroomRoute: HkeeemShowroomRoute,
  MapsRoute: MapsRoute,
  MarketRoute: MarketRoute,
  NotificationsRoute: NotificationsRoute,
  OfficeRoute: OfficeRoute,
  PrivacyRoute: PrivacyRoute,
  ProRoute: ProRoute,
  RealEstateRoute: RealEstateRoute,
  RewardsRoute: RewardsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  ShowroomRoute: ShowroomRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SmartListRoute: SmartListRoute,
  SocialOffersRoute: SocialOffersRoute,
  StoresRoute: StoresRoute,
  SyncPartnersRoute: SyncPartnersRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  HkeeemChatRoute: HkeeemChatRoute,
  HkeeemNearbyRoute: HkeeemNearbyRoute,
  HkeeemProductRoute: HkeeemProductRoute,
  HkeeemIndexRoute: HkeeemIndexRoute,
  ApiPublicGoDealIdRoute: ApiPublicGoDealIdRoute,
  ApiPublicHooksDailyContentSyncRoute: ApiPublicHooksDailyContentSyncRoute,
  ApiPublicHooksDealPushRoute: ApiPublicHooksDealPushRoute,
  ApiPublicHooksHarajSyncRoute: ApiPublicHooksHarajSyncRoute,
  ApiPublicHooksOfficePicksRoute: ApiPublicHooksOfficePicksRoute,
  ApiPublicHooksSearchConsoleSnapshotRoute:
    ApiPublicHooksSearchConsoleSnapshotRoute,
  ApiPublicHooksShowroomSyncRoute: ApiPublicHooksShowroomSyncRoute,
  ApiPublicHooksSocialSyncRoute: ApiPublicHooksSocialSyncRoute,
  ApiPublicHooksStoreBotRoute: ApiPublicHooksStoreBotRoute,
  ApiPublicHooksSyncExternalDealsRoute: ApiPublicHooksSyncExternalDealsRoute,
  ApiPublicHooksWeeklyReportRoute: ApiPublicHooksWeeklyReportRoute,
  ApiPublicPostbackNetworkRoute: ApiPublicPostbackNetworkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
